const PERMISSIONS = {
    "SUBGREDDIIT_MODERATOR" : "SUBGREDDIIT_MODERATOR",
    "SUBGREDDIIT_CREATOR" : "SUBGREDDIIT_CREATOR",
    "SUBGREDDIIT_MEMBER" : "SUBGREDDIIT_MEMBER",  
    "SUBGREDDIIT_BANNED" : "SUBGREDDIIT_BANNED",
    "USER" : "USER",
    "ADMIN" : "ADMIN",
    
}
export default PERMISSIONS;